import type { NextPage } from "next";
import Head from "next/head";
import Link from 'next/link';
import { RootState, SagaStore, wrapper } from "../store/store";
import { placesGetCountriesAction } from "../store/actions/places/placesActions";
import { END } from "redux-saga";

const Test: NextPage<RootState> = (props: RootState) => {
	console.log('PROPS FROM TEST PAGE');
	// console.log(props);
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
				<Link href="/">Back to first page</Link>
				{Object.entries(props.places.countries).map(([key, value]) => {
					return <div key={key}>{value.name}</div>;
				})}
			</main>
		</div>
	);
};

// getStaticProps
// getInitialProps
// getServerSideProps
//Test.getInitialProps

export const getServerSideProps = wrapper.getServerSideProps(
    (store) =>
        async ({ req, res }) => {
			console.log('REQUEST : ');
			console.log(req.cookies);
			console.log('RESPONSE : ');
			console.log(res);
			console.log('DISPATCHED from next server');
            store.dispatch(await placesGetCountriesAction());
			// end the saga
			await store.dispatch(END);
			await (store as SagaStore).sagaTask?.toPromise();
            return {
                props: store.getState(),
            };
        }
);

export default Test;
