import type { NextPage } from 'next';
import Head from 'next/head';
// import { getCookie } from "cookies-next";
// import {wrapper} from '../store/store';
// import {getCookie, getCookies, setCookie} from "cookies-next";
import useSWR from 'swr';
import Link from 'next/link';
import { RootState } from "../store/store";
// import { placesGetCountriesAction } from "../store/actions/places/placesActions";
// import { END } from "redux-saga";

const fetcher = (url: string) =>
	fetch(url, {
		method: 'POST',
		body: JSON.stringify({
			token: 'TEST_TOKEN_POST_REQUEST',
			maxAge: 100,
		}),
	}).then((res: Response) => res.text());

// const geter = (url: string) =>
// 	fetch(url, {
// 		method: 'GET',
// 	}).then((res: Response) => res.text());


const Home: NextPage<RootState> = () => {
	// console.log('props from getServerSideProps');
	// console.log(props.places.countries);

	// const { data, error } = useSWR('/api/cookies', geter);
	// console.log(data);
	// console.log(error);
	// if (error) return <div>Failed to load</div>;
	// if (!data) return <div>Loading...</div>;

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
				{/*<div>{`Cookie from response: "${data}"`}</div>*/}
				<Link href="/">To second page</Link>
			</main>
		</div>
	);
};



// getStaticProps
// getInitialProps

// export const getServerSideProps = ({ req, res }) => {
//     // setCookie('test', 'value', { req, res, maxAge: 60 * 6 * 24 });
//     const cookie = getCookie('test_cookie', { req, res });
//     console.log(cookie);
//     // getCookies({ req, res });
//     // deleteCookie('test', { req, res });
//     return { props: {} };
// };

export default Home;
