import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { RootState } from "../store/store";


const Home: NextPage<RootState> = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
				{/*<div>{`Cookie from response: "${data}"`}</div>*/}
				<Link href="/">To second page</Link>
			</main>
		</div>
	);
};



// getStaticProps
// getInitialProps

// export const getServerSideProps = ({ req, res }) => {
//     // setCookie('test', 'value', { req, res, maxAge: 60 * 6 * 24 });
//     const cookie = getCookie('test_cookie', { req, res });
//     console.log(cookie);
//     // getCookies({ req, res });
//     // deleteCookie('test', { req, res });
//     return { props: {} };
// };

export default Home;
